version: 1
services:
  - name: Rarytas_RestaurantSide
    source:
      type: image
      image: public.ecr.aws/amazonlinux/amazonlinux:2
    environment:
      - name: PORT
        value: '8082'
    runtime:
      runtime: java
      runtimeVersion: 20
    build:
      command: |
        wget -q https://downloads.apache.org/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz -O tomcat.tar.gz
        tar xfz tomcat.tar.gz
        mv apache-tomcat-9.0.54 tomcat

        cp Rarytas_RestaurantSide-0.0.1-SNAPSHOT.war tomcat/webapps/

        ./tomcat/bin/catalina.sh run
    port: 8082